//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rxWebReport.frmRx.Agyliti.Cliente001.DevExtreme.cnRxApp.app01JS
{


    public partial class cnRxAppApp01JS
    {
    }
}
