using System;

namespace rxWebReport.Domain.Entities
{
    public class GetLockMessageAckGetStatusView
    {
        public long Id { get; set; }
        public string TopicDeviceId { get; set; }
        public string CofreNome { get; set; }
        public int Destiny { get; set; }
        public long DeviceStatus { get; set; }
        public int DeviceStatusBit0 { get; set; }
        public int DeviceStatusBit1 { get; set; }
        public int DeviceStatusBit2 { get; set; }
        public int DeviceStatusBit3 { get; set; }
        public int DeviceStatusBit4 { get; set; }
        public int DeviceStatusBit5 { get; set; }
        public int DeviceStatusBit6 { get; set; }
        public int DeviceStatusBit7 { get; set; }
        public int DeviceStatusBit8 { get; set; }
        public int DeviceStatusBit9 { get; set; }
        public int DeviceStatusBit10 { get; set; }
        public int DeviceStatusBit11 { get; set; }
        public int DeviceStatusBit12 { get; set; }
        public int DeviceStatusBit13 { get; set; }
        public int DeviceStatusBit14 { get; set; }
        public int DeviceStatusBit15 { get; set; }
        public int DeviceStatusBit16 { get; set; }
        public int DeviceStatusBit17 { get; set; }
        public int DeviceStatusBit18 { get; set; }
        public int DeviceStatusBit19 { get; set; }
        public int DeviceStatusBit20 { get; set; }
        public int DeviceStatusBit21 { get; set; }
        public int DeviceStatusBit22 { get; set; }
        public int DeviceStatusBit23 { get; set; }
        public int DeviceStatusBit24 { get; set; }
        public int DeviceStatusBit25 { get; set; }
        public int DeviceStatusBit26 { get; set; }
        public int DeviceStatusBit27 { get; set; }
        public int DeviceStatusBit28 { get; set; }
        public int DeviceStatusBit29 { get; set; }
        public int DeviceStatusBit30 { get; set; }
        public int DeviceStatusBit31 { get; set; }
        public long BillMachineStatus { get; set; }
        public int BillMachineStatusBit0 { get; set; }
        public int BillMachineStatusBit1 { get; set; }
        public int BillMachineStatusBit2 { get; set; }
        public int BillMachineStatusBit3 { get; set; }
        public int BillMachineStatusBit4 { get; set; }
        public int BillMachineStatusBit5 { get; set; }
        public int BillMachineStatusBit6 { get; set; }
        public int BillMachineStatusBit7 { get; set; }
        public int BillMachineStatusBit8 { get; set; }
        public int BillMachineStatusBit9 { get; set; }
        public int BillMachineStatusBit10 { get; set; }
        public int BillMachineStatusBit11 { get; set; }
        public int BillMachineStatusBit12 { get; set; }
        public int BillMachineStatusBit13 { get; set; }
        public int BillMachineStatusBit14 { get; set; }
        public int BillMachineStatusBit15 { get; set; }
        public int BillMachineStatusBit16 { get; set; }
        public int BillMachineStatusBit17 { get; set; }
        public int BillMachineStatusBit18 { get; set; }
        public int BillMachineStatusBit19 { get; set; }
        public int BillMachineStatusBit20 { get; set; }
        public int BillMachineStatusBit21 { get; set; }
        public int BillMachineStatusBit22 { get; set; }
        public int BillMachineStatusBit23 { get; set; }
        public int BillMachineStatusBit24 { get; set; }
        public int BillMachineStatusBit25 { get; set; }
        public int BillMachineStatusBit26 { get; set; }
        public int BillMachineStatusBit27 { get; set; }
        public int BillMachineStatusBit28 { get; set; }
        public int BillMachineStatusBit29 { get; set; }
        public int BillMachineStatusBit30 { get; set; }
        public int BillMachineStatusBit31 { get; set; }
        public long BillMachineError { get; set; }
        public int BillMachineErrorBit0 { get; set; }
        public int BillMachineErrorBit1 { get; set; }
        public int BillMachineErrorBit2 { get; set; }
        public int BillMachineErrorBit3 { get; set; }
        public int BillMachineErrorBit4 { get; set; }
        public int BillMachineErrorBit5 { get; set; }
        public int BillMachineErrorBit6 { get; set; }
        public int BillMachineErrorBit7 { get; set; }
        public int BillMachineErrorBit8 { get; set; }
        public int BillMachineErrorBit9 { get; set; }
        public int BillMachineErrorBit10 { get; set; }
        public int BillMachineErrorBit11 { get; set; }
        public int BillMachineErrorBit12 { get; set; }
        public int BillMachineErrorBit13 { get; set; }
        public int BillMachineErrorBit14 { get; set; }
        public int BillMachineErrorBit15 { get; set; }
        public int BillMachineErrorBit16 { get; set; }
        public int BillMachineErrorBit17 { get; set; }
        public int BillMachineErrorBit18 { get; set; }
        public int BillMachineErrorBit19 { get; set; }
        public int BillMachineErrorBit20 { get; set; }
        public int BillMachineErrorBit21 { get; set; }
        public int BillMachineErrorBit22 { get; set; }
        public int BillMachineErrorBit23 { get; set; }
        public int BillMachineErrorBit24 { get; set; }
        public int BillMachineErrorBit25 { get; set; }
        public int BillMachineErrorBit26 { get; set; }
        public int BillMachineErrorBit27 { get; set; }
        public int BillMachineErrorBit28 { get; set; }
        public int BillMachineErrorBit29 { get; set; }
        public int BillMachineErrorBit30 { get; set; }
        public int BillMachineErrorBit31 { get; set; }

        public long LevelSensor { get; set; }
        public long UptimeSec { get; set; }
        public string Timestamp { get; set; }
        public bool IsAck { get; set; }
        public Nullable<System.DateTime> TimestampDatetime { get; set; }
        public Nullable<System.DateTime> trackLastWriteTime { get; set; }
        public Nullable<System.DateTime> trackCreationTime { get; set; }
    }
}