//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace rxWebReport
{
    using System;
    using System.Collections.Generic;
    
    public partial class cofre_user
    {
        public long id { get; set; }
        public string id_cofre { get; set; }
        public string data_user { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> trackLastWriteTime { get; set; }
        public Nullable<System.DateTime> trackCreationTime { get; set; }
    }
}
