// <auto-generated />
namespace rxWebReport.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class v030 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v030));
        
        string IMigrationMetadata.Id
        {
            get { return "202306241704568_v030"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
